config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :users
  resources :catergories do
    resources :spendings
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "users#splash"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    return unless user.present?

    can :manage, Spending, author: user
    can :manage, Catergory, user_id: user.id
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/catergory.rb
class Catergory < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :spendings, dependent: :destroy

  validates :name, presence: true, length: { maximum: 255 }

  def total_amount
    spendings.sum('amount')
  end
end

app/models/spending.rb
class Spending < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_and_belongs_to_many :catergories, dependent: :destroy

  validates :name, :amount, presence: true, length: { maximum: 255 }
  validates :amount, numericality: { greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :spendings, dependent: :destroy
  has_many :catergories, dependent: :destroy

  validates :name, presence: true, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  def after_sign_in_path_for(resource)
    catergories_path if resource.is_a?(User)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[email password password_confirmation name])
    devise_parameter_sanitizer.permit(:sign_in, keys: %i[email password])
  end
end

app/controllers/spendings_controller.rb
class SpendingsController < ApplicationController
  def index
    @spending = Spending.all.includes([:user]).where(user_id: current_user.id).order(:name)
  end

  def new
    @spending = Spending.new
  end

  def create
    @user = current_user
    @spending = @user.spendings.new(spending_params)
    if @spending.save
      flash[:notice] = 'Spending created successfully'
      @catergory_spending = @spending.catergory_spendings.create(catergory_id: params[:catergory_id],
                                                                 spending_id: @spending.id)
      redirect_to catergories_path
    else
      render 'new'
    end
  end

  def show
    @spending = Spending.find(params[:id])
  end

  private

  def spending_params
    params.permit(:name, :amount)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all.order(created_at: :desc)
  end

  def splash; end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/catergories_helper.rb
module CatergoriesHelper
end

app/helpers/spendings_helper.rb
module SpendingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/spendings/_header.html.erb
<header>
  <div class="row">
    <div class="col m-1">
      <a href="/catergories">
        <span class="material-symbols-outlined">
          back
          </span>
      </a>
    </div>
    <div class="col m-1 d-flex flex-column align-items-center pg_title">
      <h3 class=' p-4 text-success font-weight-bold'><b>BUDGET</b></h3>
    </div>
    <div class="col">
    </div>
  </div>
</header>

app/views/spendings/_new.html.erb
<header class="d-flex flex-column justify-content-center">
    <div>
      <h3 class='m-5 p-4 text-success font-weight-bold'><b>NEW BUDGET</b></h3>
  </div>
</header>

app/views/spendings/_spending_card.html.erb
<div class="container">
  <table class="table table-striped", style="text-align: center;">
    <thead>
      <tr>
        <th>No.</th>
        <th>Name</th>
        <th>Amount</th>
      </tr>
    </thead>
    <tbody>
      <% @catergory.spendings.each_with_index do |spending, index| %>
        <tr>
          <td><%= index + 1 %></td>
          <td><%= spending.name %></td>
          <td>$ <%= spending.amount %></td>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
    </div>
</div>

app/views/spendings/index.html.erb
<h1>All budgets are here</h1>

app/views/spendings/new.html.erb
<div class="d-flex flex-column align-items-center">
<%= render "spendings/new" %>
</div>
<div class="container d-flex flex-column justify-content-center align-items-center">

  <%= form_with model: @spendings, url: catergory_spendings_path, method: :post, data: { turbo: false } do |f| %>
    <div class="form-group p-2">
        <%= f.text_field :name, autofocus: true, autocomplete: "name" , class: "form-control", placeholder: "Spending Name" %>
    </div>
    <div class="form-group p-2">
      <%= f.text_field :amount, autofocus: true, autocomplete: "name" , class: "form-control", placeholder: "Amount in numbers" %>
    </div>

    <div class="form-group p-2">
      <%= f.submit "SAVE" , class: "form-control btn btn-success" %>
    </div>
  <% end %>
   <a href="/catergories">
        <span class="material-symbols-outlined">
          back
          </span>
  </a>