config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :users
  resources :catergories do
    resources :spendings
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "users#splash"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    return unless user.present?

    can :manage, Spending, author: user
    can :manage, Catergory, user_id: user.id
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/catergory.rb
class Catergory < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :spendings, dependent: :destroy

  validates :name, presence: true, length: { maximum: 255 }

  def total_amount
    spendings.sum('amount')
  end
end

app/models/spending.rb
class Spending < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_and_belongs_to_many :catergories, dependent: :destroy

  validates :name, :amount, presence: true, length: { maximum: 255 }
  validates :amount, numericality: { greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :spendings, dependent: :destroy
  has_many :catergories, dependent: :destroy

  validates :name, presence: true, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  def after_sign_in_path_for(resource)
    catergories_path if resource.is_a?(User)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[email password password_confirmation name])
    devise_parameter_sanitizer.permit(:sign_in, keys: %i[email password])
  end
end

app/controllers/spendings_controller.rb
class SpendingsController < ApplicationController
  def index
    @spending = Spending.all.includes([:user]).where(user_id: current_user.id).order(:name)
  end

  def new
    @spending = Spending.new
  end

  def create
    @user = current_user
    @spending = @user.spendings.new(spending_params)
    if @spending.save
      flash[:notice] = 'Spending created successfully'
      @catergory_spending = @spending.catergory_spendings.create(catergory_id: params[:catergory_id],
                                                                 spending_id: @spending.id)
      redirect_to catergories_path
    else
      render 'new'
    end
  end

  def show
    @spending = Spending.find(params[:id])
  end

  private

  def spending_params
    params.permit(:name, :amount)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all.order(created_at: :desc)
  end

  def splash; end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/catergories_helper.rb
module CatergoriesHelper
end

app/helpers/spendings_helper.rb
module SpendingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/catergories/_catergory_card.html.erb
<div class="card d-flex flex-column justify-content-center align-items-center m-3 pt-3" style="width: 18rem;">
  <div>
    <% if catergory.icon %>
    <span class="material-symbols-outlined img">
      <%= catergory.icon %>
      </span>
  </div>
  <% end %>
  <div class="card-body d-flex flex-column justify-content-center align-items-center">
    <h5 class="card-title badge text-bg-warning p-2 px-4"><%= catergory.name %></h5>
    <p class="card-text pt-2">Total Amount Allotted: $
      <%= catergory.spendings.sum(:amount) %>
    </p>
    <p class="card-text opacity-50"><%= time_ago_in_words(catergory[:created_at]) %></p>
    <%= button_to "SELECT", catergory_path(catergory), method: :get, class: "btn btn-success" %>
  </div>
</div>

app/views/catergories/_header.html.erb
<header>
  <div class="row">
    <div class="col m-1">
      <a href="/">
        <span class="material-symbols-outlined">
          back
          </span>
      </a>
    </div>
    <div class="col m-1 d-flex flex-column align-items-center pg_title">
      <h3 class="mb-0">CATERGORY</h3>
    </div>
    <div class="col">
    </div>
  </div>
</header>

app/views/catergories/_new.html.erb
<header>
  <div class="row">
    <div class="col m-1">
      <a href="/groups">
        <span class="material-symbols-outlined">
          back
          </span>
      </a>
    </div>
    <div class="col m-1 d-flex flex-column align-items-center pg_title">
      <h3 class='m-3 p-4 text-success font-weight-bold'><b>NEW CATEGORY</b></h3>
    </div>
    <div class="col">
    </div>
  </div>
</header>

app/views/catergories/index.html.erb
<div class="container d-flex flex-column justify-content-center align-items-center">
  <% @catergories.each do |catergory| %>
    <%= render partial: 'catergories/catergory_card', locals: { catergory: catergory } %>
  <% end %>
  <% if @catergories.empty? %>
  <h1>There are no catergories to show</h1>
  <% end %>
  <%= link_to "Add New Category", new_catergory_path, class: "btn btn-success mb-5" %>

</div>

app/views/catergories/new.html.erb
<%= render "catergories/new" %>
<div class="container d-flex flex-column justify-content-center align-items-center">

  <%= form_with model: @catergories, url: catergories_path, method: :post, data: { turbo: false } do |f| %>
    <div class="form-group p-3">
        <%= f.text_field :name, autofocus: true, autocomplete: "name" , class: "form-control", placeholder: "Category Name" %>
    </div>
    <div class="form-group p-3">
      <%= f.select :icon, @icons, { include_blank: 'Please select an icon' }, class: "form-select" %>
    </div>

    <div class="form-group p-3">
      <%= f.submit "SAVE" , class: "form-control btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/catergories/show.html.erb
<%= render "spendings/header" %>
<div class="d-flex flex-column justify-content-center align-items-center m-3 pt-3">
  <div class="card d-flex flex-column justify-content-center align-items-center m-3 pt-3" style="width: 18rem;">
    <div>
    <% if @catergory.icon %>
    <span class="material-symbols-outlined img">
      <%= @catergory.icon %>
      </span>
  </div>
  <% end %>
  <div class="card-body d-flex flex-column justify-content-center align-items-center">
    <h5 class="card-title badge text-bg-warning p-2 px-4"><%= @catergory.name %></h5>
    <p class="card-text">Total Amount Allocated: $ <%= @catergory.spendings.sum(:amount) %></p>
    <p class="card-text opacity-50"><%= time_ago_in_words(@catergory[:created_at]) %></p>
  </div>
</div>
<%= link_to "Add New Budget", new_catergory_spending_path(@catergory), class: "btn btn-success mb-5" %>
<% if @catergory.spendings.any? %>
<h1>All Allocated Budgets</h1>
    <%= render partial: 'spendings/spending_card', locals: { category: @catergory } %>
     <% else %>
    <h1>No Budgets Yet</h1>
<% end %>